"use client";

import * as React from "react";
import { Download, Share2, Loader2 } from "lucide-react";
import { Modal } from "@/components/ui/modal";
import { Button } from "@/components/ui/button";
import { useToast } from "@/components/ui/toast";
import type { Product, Store } from "@/lib/types";

/**
 * "Share to Status" — shows a 1080x1920 marketing image for a product
 * (generated by /api/og/product) and lets the seller download it or share it
 * via the Web Share API. Pure marketing image + link; no ordering/chat.
 */
export function ShareStatusModal({
  open,
  onClose,
  product,
  store,
}: {
  open: boolean;
  onClose: () => void;
  product: Product | null;
  store: Store;
}) {
  const toast = useToast();
  const [imgLoaded, setImgLoaded] = React.useState(false);
  const [busy, setBusy] = React.useState(false);

  React.useEffect(() => {
    if (open) setImgLoaded(false);
  }, [open, product?.id]);

  if (!product) return null;

  const src = `/api/og/product?store=${encodeURIComponent(
    store.store_name
  )}&product=${encodeURIComponent(product.id)}`;
  const fileName = `mystorr-${store.store_name}-${product.id}.png`;

  async function fetchFile(): Promise<File> {
    const res = await fetch(src);
    if (!res.ok) throw new Error("Could not generate image");
    const blob = await res.blob();
    return new File([blob], fileName, { type: "image/png" });
  }

  function triggerDownload(blob: Blob) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  async function handleDownload() {
    setBusy(true);
    try {
      const file = await fetchFile();
      triggerDownload(file);
    } catch {
      toast("Could not download image. Try again.", "error");
    } finally {
      setBusy(false);
    }
  }

  async function handleShare() {
    setBusy(true);
    try {
      const file = await fetchFile();
      const nav = navigator as Navigator & {
        canShare?: (data?: ShareData) => boolean;
      };
      if (nav.canShare && nav.canShare({ files: [file] })) {
        await nav.share({
          files: [file],
          title: product!.name,
          text: `${product!.name} — order on my Mystorr shop`,
        });
      } else {
        // No file-share support (most desktops) — fall back to download.
        triggerDownload(file);
        toast("Sharing isn't supported here — image downloaded instead.", "success");
      }
    } catch (err) {
      // User cancelling the share sheet throws AbortError — ignore that.
      if (!(err instanceof DOMException && err.name === "AbortError")) {
        toast("Could not share image. Try downloading instead.", "error");
      }
    } finally {
      setBusy(false);
    }
  }

  return (
    <Modal open={open} onClose={onClose} title="Share to Status">
      <p className="text-sm text-muted">
        A ready-to-post image for WhatsApp Status, Instagram Stories and more —
        with a link back to your shop.
      </p>

      <div className="relative mx-auto mt-4 aspect-[9/16] w-full max-w-[260px] overflow-hidden rounded-xl border border-line bg-background">
        {!imgLoaded && (
          <div className="absolute inset-0 flex items-center justify-center">
            <Loader2 className="h-6 w-6 animate-spin text-muted" />
          </div>
        )}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={src}
          alt={`${product.name} status preview`}
          onLoad={() => setImgLoaded(true)}
          className="h-full w-full object-cover"
        />
      </div>

      <div className="mt-4 flex gap-2">
        <Button
          variant="outline"
          className="flex-1"
          onClick={handleDownload}
          loading={busy}
        >
          {!busy && <Download className="h-4 w-4" />} Download
        </Button>
        <Button
          variant="brand"
          className="flex-1"
          onClick={handleShare}
          loading={busy}
        >
          {!busy && <Share2 className="h-4 w-4" />} Share
        </Button>
      </div>
    </Modal>
  );
}
